//POSTGRES_USER=example
//POSTGRES_PASSWORD=examplepwd.
//POSTGRES_DB=exampledb
//POSTGRES_LISTEN_ADDRESS=localhost


//postgressdb
POSTGRES_USER=example
POSTGRES_PASSWORD=examplepwd
POSTGRES_DB=exampledb
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

//rabbitmq
RABBITMQ_USERNAME=user2
RABBITMQ_PASSWORD=password
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_URL='amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/'

//mongo
//MONGO_INITDB_ROOT_USERNAME
//MONGO_INITDB_ROOT_PASSWORD
Username=admin
Password=Password123
MONGO_PORT=27017
MONGO_DB=logs
MONGO_HOST=localhost
MONGO_URL='mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}'

